# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SigFunction
                                 A QGIS plugin
 SIGfunction uses a mathematical expression to transform the natural scale that measures the state of a territory attribute to a value scale between zero and one, which represents a gradient from an anti-ideal state to an ideal one according to its contribution to compliance. of the objective or goal (0 representing the most undesirable condition and 1 the most desirable

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-07
        copyright            : (C) 2024 by Víctor Hernández Díaz / UNAM-LANCIS-APC
        email                : victorhdzgeo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SigFunction class from file SigFunction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sigfunction import SigFunction
    return SigFunction(iface)
